### ISSUE TITLE
inter india exchange arbitrage

### ISSUE THREAD

**Issue by test2a** [theagilecoder/arbit#2]
Came across your project. Good work is being done. I Tried the online demo website but i could only find usa to india and vice versa arbitrage. Can you do inter india arbitrage?  like between zebpay, coindcx. wazirx and bitbns only?

**Comment by theagilecoder** [comment]
Theoretically speaking, yes intra-India arbitrage is possible. However, practically speaking, the arbitrage differences are so low (1% on a good day), it's not worth the while. Unfortunately, money making opportunity lies only in cross-border arbitrage where arbitarge differences are daily in the 5-10 % range.
